version: '3.8'

services:
  redis_pesk:
    image: redis:7-alpine
    container_name: redis_pesk
    ports:
      - "6379:6379"
    restart: unless-stopped

  db_pesk:
    image: postgres:16
    container_name: db_pesk
    restart: unless-stopped
    ports:
      - "5440:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
    volumes:
      - db_pesk:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_POSTGRES_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  fastapi_app:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db_pesk
      DB_NAME: ${DB_NAME}
      DB_POSTGRES_USER: ${DB_POSTGRES_USER}
      DB_POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
      DB_PORT: 5432
      REDIS_HOST: redis_pesk
      REDIS_PORT: 6379
    env_file:
      - .env
    volumes:
      - ./src:/app
    depends_on:
      db_pesk:
        condition: service_healthy



volumes:
  db_pesk: